# Generated by Django 6.0.5 on 2026-06-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor_quicku', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='udla123', max_length=128),
        ),
    ]
